version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/tqi_jtorres/Documents/Estudos/prometheus_e_grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    user: "${UID}"
    volumes:
      - /home/tqi_jtorres/Documents/Estudos/prometheus_e_grafana/grafana:/var/lib/grafana
    restart: unless-stopped