{
 "title": "Aula",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Usuários logados",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "aula_usuarios_logados_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(aula_requests_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de resposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(aula_request_duration_seconds_bucket[1m]))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, rate(aula_request_duration_seconds_bucket[1m]))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.9, rate(aula_request_duration_seconds_bucket[1m]))",
     "legendFormat": "90%"
    }
   ]
  },
  {
   "title": "requests/segundos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(aula_requests_total[1m]))",
     "legendFormat": "API"
    }
   ]
  },
  {
   "title": "Taxa de erro da API",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(aula_requests_total{statusCode=\"500\"}[1m])) / sum(rate(aula_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}